---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---

## 網站資料爬取
```{r}
library(rvest) ##第一次使用要先安裝
##read_html
tmp <- "https://www.ptt.cc/bbs/NBA/index"
totalFrame <- NULL
for(i in 4627:1){
  PTT_NBAUrl <- paste0(tmp, as.character(i), ".html")
  NBAContent <- read_html(PTT_NBAUrl)
  NBAPostTitle <- NBAContent %>%  html_nodes(".title") %>% html_text() 
  NBAPostAuthor <- NBAContent %>% html_nodes(".author") %>% html_text()
  NBAPostPushNum <- NBAContent %>% html_nodes(".nrec") %>% html_text()
  tmpFrame <- data.frame(Order = c(1:length(NBAPostTitle)), ## for ranking the post according post time
                         Title = NBAPostTitle, 
                         Author = NBAPostAuthor,
                         PushNum = NBAPostPushNum)
                         #Url = PTT_NBAUrl
  tmpFrame <- tmpFrame[order(tmpFrame$Order, decreasing = T),] ## reverse the order the tmpFrame
  rownames(tmpFrame) <- c(1:nrow(tmpFrame)) ## reassign the rownames()
  
  totalFrame <- rbind(totalFrame, tmpFrame) ## integrate tmpFrame to totalFrame
  if(nrow(totalFrame) > 100){ ## over 100 post
    break
  }
}
totalFrame$Order <- NULL ## delete the Order column


##html_nodes 
##html_text
```

## 爬蟲結果呈現
```{r}
#這是R Code Chunk
knitr::kable(totalFrame) ##請將iris取代為上個步驟中產生的爬蟲資料資料框
```

## 解釋爬蟲結果 
```{r}
#這是R Code Chunk
# - 用文字搭配程式碼解釋爬蟲結果
#    - 共爬出幾篇文章標題？（程式碼與文字解釋各`5pt`）
#        - dim(), nrow(), str()皆可
com1 <- paste0("A total of  ", as.character(nrow(totalFrame)), " titles were acquired from PTT/NBA.")
print(com1)

#    - 哪個作者文章數最多？（程式碼與文字解釋各`5pt`）
#        - table()
table.fre.author <- sort(table(totalFrame$Author, dnn = "AuthorName"), decreasing = T)
com2 <- paste0("Author who posted the most is ", attr(table.fre.author[1], "names"), ".")
print(com2)

```

A total of  120 titles were acquired from PTT/NBA.

Author who posted the most is Rambo.

```{r}
#這是R Code Chunk
#    - 其他爬蟲結果解釋（`10pt`）
#        - 試著找出有趣的現象，不一定要用程式碼搭配解釋，也可只用文字
totalFrame.TheMostAuthor <- subset(totalFrame, Author == attr(table.fre.author[1], "names"))
knitr::kable(totalFrame.TheMostAuthor)
print("The posts by Rambo include Box, Live, and Standing.")

```
The posts by Rambo include Box, Live, and Standing.
